### ISSUE TITLE
what is the status of this repo

### ISSUE THREAD

**Issue by vincentsarago** [tilery/python-vtzero#1]
Hi @yohanboniface, 
I know you have a ton on your plate but I wanted to know if you had more though about this repo ? right now the lib doesn't compile but I think it's because some change on vtzero or Protozero libs.

Personally I wanted to try this to see if it outperformed the pure python https://github.com/mapbox/vector-tile-base lib.

I'll try to fix the compilation issue and open a PR as soon as I fix it (if I succeed)

**Comment by yohanboniface** [comment]
> I'll try to fix the compilation issue and open a PR as soon as I fix it (if I succeed)

Cool, thanks @vincentsarago !

I'm missing time to put that project on top of my priorities sadly, but if you push it a bit, that may help me jumpin' in again :)

**Comment by vincentsarago** [comment]
FYI this is the error I'm seeing: 

```
vtzero/tile.cpp:6327:94: error: invalid operands to binary expression ('enum vtzero::GeomType' and 'enum vtzero::GeomType')
    const enum vtzero::GeomType neg_one = (enum vtzero::GeomType) ((enum vtzero::GeomType) 0 - (enum vtzero::GeomType) 1), const_zero = (enum vtzero::GeomType) 0;
```

I guess there was a change somewhere in the feature or geometry header, I'm still investigating

**Comment by vincentsarago** [comment]
I think the error might be from GCC and related to https://github.com/cython/cython/issues/2749

**Comment by vincentsarago** [comment]
FYI I reverted to cython 0.28.6 and it compiled fine so I guess the error is between 

https://github.com/tilery/python-vtzero/blob/master/vtzero/cvtzero.pxd#L63-L68
and
https://github.com/tilery/python-vtzero/blob/master/vtzero/tile.pyx#L10-L13

**Comment by vincentsarago** [comment]
@yohanboniface I'm going to open some issues to set up the work I'd like to do on this repo if this ok with you 😄

**Comment by yohanboniface** [comment]
> I'm going to open some issues to set up the work I'd like to do on this repo if this ok with you

Totally!

Do you want the commit bit?
