### ISSUE TITLE
Distribute to PyPI ?

### ISSUE THREAD

**Issue by vincentsarago** [tilery/python-vtzero#8]
@yohanboniface while there is still a lot of work to do with this lib, could we make it available on PyPI (as beta maybe) ?

**Comment by yohanboniface** [comment]
Sure!

Let's also add a make command so we don't need to warm old memory each time we want to release, eg. https://github.com/pyrates/autoroutes/blob/master/Makefile#L8

**Comment by vincentsarago** [comment]
@yohanboniface can I suggest we use tox ? I find tox really useful to manage testing/deploying. 
e.g https://github.com/vincentsarago/python-vtzero/blob/ci_and_deploy/tox.ini#L30-L48

**Comment by yohanboniface** [comment]
I'm a "less is more" adept, so I usually prefer to not add a tool in my toolbox unless I really can't live without.

That said, if you want to use it and are ok to maintain it over time, let's do that :)

**Comment by vincentsarago** [comment]
👍 thanks @yohanboniface really appreciate. I don't want to impose any thing but I think it really helps when it come to testing (locally / ci).
